# Generated by Django 4.0.6 on 2022-08-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksshelf', '0005_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'So-So'), (2, 'Mehh'), (3, 'Decent'), (4, 'Amazing'), (5, 'NICE')], null=True),
        ),
    ]
